{"assignees":[{"id":"MDQ6VXNlcjExMjY5ODE=","login":"wence-","name":"Lawrence Mitchell"}],"author":{"id":"MDQ6VXNlcjExMjY1Mw==","is_bot":false,"login":"mattf","name":"Matthew Farrellee"},"body":"**Describe the bug**\r\n```\r\n>>> import pandas as pd\r\n>>> import cudf\r\n>>> cudf.__version__\r\n'22.12.00a+281.gcc4b4dd27c'\r\n>>> data = {'a': ['b'], 'p': ['q'], 'n': [0]}\r\n>>> pd.DataFrame(data).groupby('a').describe()\r\n      n                                  \r\n  count mean std  min  25%  50%  75%  max\r\na                                        \r\nb   1.0  0.0 NaN  0.0  0.0  0.0  0.0  0.0\r\n>>> cudf.DataFrame(data).groupby('a').describe()\r\n      p             n                                  \r\n  count min max count mean   std min  25%  50%  75% max\r\na                                                      \r\nb     1   q   q     1  0.0  <NA>   0  0.0  0.0  0.0   0\r\n```\r\n\r\n**Environment overview (please complete the following information)**\r\nrapidsai/rapidsai-nightly:22.12-cuda11.5-runtime-rockylinux8-py3.9 on 29 nov 2022","closed":false,"closedAt":null,"comments":[{"id":"IC_kwDOBWUGps5T9bou","author":{"login":"wence-"},"authorAssociation":"CONTRIBUTOR","body":"So pandas' behaviour with groupby-agg is to drop any column from the dataframe where any requested agg is not supported. In contrast, cudf only drops the column if _all_ aggs are unsupported. So this is probably easy to mimic the pandas behaviour (assuming that my description is complete in their treatment).","createdAt":"2023-01-30T13:14:59Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/12263#issuecomment-1408612910","viewerDidAuthor":false}],"createdAt":"2022-11-30T00:51:25Z","id":"I_kwDOBWUGps5XjYdZ","labels":[{"id":"MDU6TGFiZWw1OTk2MjY1NTk=","name":"bug","description":"Something isn't working","color":"d73a4a"},{"id":"MDU6TGFiZWwxMDEzOTg3MzUy","name":"0 - Backlog","description":"In queue waiting for assignment","color":"d4c5f9"},{"id":"MDU6TGFiZWwxMTM5NzQxMjEz","name":"cuDF (Python)","description":"Affects Python cuDF API.","color":"1d76db"}],"milestone":{"number":5,"title":"Pandas API Alignment and Coverage","description":"","dueOn":null},"number":12263,"projectCards":[{"project":{"name":"Bug Squashing"},"column":{"name":"Backlog"}}],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[BUG] DataFrame.groupby.describe differs between cudf and pandas","updatedAt":"2024-05-16T05:12:37Z","url":"https://github.com/rapidsai/cudf/issues/12263"}
