{"assignees":[{"id":"MDQ6VXNlcjUzNzk2MDk5","login":"brandon-b-miller","name":""}],"author":{"id":"MDQ6VXNlcjUzNzk2MDk5","is_bot":false,"login":"brandon-b-miller","name":""},"body":"**Is your feature request related to a problem? Please describe.**\r\nIn pandas, we can check if the values of a series or dataframe are contained within some other container, like a list or dataframe, by using `isin`. Currently, this doesn't work correctly for nulls. On branch-0.19, if the dataframe or series we're checking contains an `<NA>`, we get a `False`:\r\n\r\n```\r\n>>> values = cudf.Series([1,2,3])\r\n>>> df = cudf.DataFrame({'a':[1,2,None]})\r\n>>> df\r\n      a\r\n0     1\r\n1     2\r\n2  <NA>\r\n>>> df.isin(values)\r\n       a\r\n0   True\r\n1   True\r\n2  False\r\n```\r\n\r\nWhere we should get just another `<NA>` there, like in pandas, using nullable dtypes: \r\n\r\n```\r\n>>> values = pd.Series([1,2,3], dtype='Int64')\r\n>>> df = pd.DataFrame({'a':pd.Series([1,2,None], dtype='Int64')})\r\n>>> df\r\n      a\r\n0     1\r\n1     2\r\n2  <NA>\r\n>>> df.isin(values)\r\n      a\r\n0  True\r\n1  True\r\n2  <NA>\r\n```\r\n\r\nWhile the `fillna` that causes us to get `False` is being removed in PR https://github.com/rapidsai/cudf/pull/7490, we'll need to rework how we're testing this functionality and change it to test against nullable types. It just so happens that when using non nullable pandas types, we get `False` as well - hence our results lining up so far. \r\n\r\n\r\n**Describe the solution you'd like**\r\nWe should get an `<NA>` everywhere the series or dataframe in question already has an `<NA>` and our tests should be updated to reflect that. \r\n\r\n\r\n**Describe alternatives you've considered**\r\nWe could change it as part of PR https://github.com/rapidsai/cudf/pull/7490 but it would be somewhat tangential to the point. \r\n\r\n\r\n**Additional context**\r\nAdd any other context, code examples, or references to existing implementations about the feature request here.\r\n","closed":false,"closedAt":null,"comments":[{"id":"MDEyOklzc3VlQ29tbWVudDgxNjk3MTAyMg==","author":{"login":"github-actions"},"authorAssociation":"NONE","body":"This issue has been labeled `inactive-30d` due to no recent activity in the past 30 days. Please close this issue if no further response or action is needed. Otherwise, please respond with a comment indicating any updates or changes to the original issue and/or confirm this issue still needs to be addressed. This issue will be labeled `inactive-90d` if there is no activity in the next 60 days.","createdAt":"2021-04-09T21:04:39Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/7556#issuecomment-816971022","viewerDidAuthor":false},{"id":"IC_kwDOBWUGps49geUm","author":{"login":"github-actions"},"authorAssociation":"NONE","body":"This issue has been labeled `inactive-90d` due to no recent activity in the past 90 days. Please close this issue if no further response or action is needed. Otherwise, please respond with a comment indicating any updates or changes to the original issue and/or confirm this issue still needs to be addressed.","createdAt":"2022-02-07T21:05:25Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/7556#issuecomment-1031922982","viewerDidAuthor":false},{"id":"IC_kwDOBWUGps5srHbm","author":{"login":"wence-"},"authorAssociation":"CONTRIBUTOR","body":"Amusingly this only happens with `DataFrame.isin`, if asking `isin` of _`Series`_ objects, pandas does like cudf.","createdAt":"2023-11-22T18:04:16Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/7556#issuecomment-1823241958","viewerDidAuthor":false}],"createdAt":"2021-03-10T20:22:41Z","id":"MDU6SXNzdWU4MjgyODkyMjg=","labels":[{"id":"MDU6TGFiZWw1OTk2MjY1NjE=","name":"feature request","description":"New feature or request","color":"a2eeef"},{"id":"MDU6TGFiZWwxMTM5NzQxMjEz","name":"cuDF (Python)","description":"Affects Python cuDF API.","color":"1d76db"}],"milestone":null,"number":7556,"projectCards":[{"project":{"name":"v22.12 Release"},"column":{"name":"Issue-P2"}}],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[FEA] Propagate nulls through `isin` ","updatedAt":"2024-02-23T18:43:07Z","url":"https://github.com/rapidsai/cudf/issues/7556"}
