{"assignees":[],"author":{"id":"MDQ6VXNlcjI2MTY5Nzcx","is_bot":false,"login":"miguelusque","name":"Miguel MartÃ­nez"},"body":"**Describe the bug**\r\nHi\r\n\r\nWhile porting some code from Pandas, I have noticed that the column types after `cudf.crosstab()` does not match Pandas result.\r\n\r\nPlease, see a reproducer below:\r\n\r\n```python\r\n> > import cudf\r\n> > import pandas as pd\r\n> > \r\n> > print(cudf.__version__, pd.__version__, '\\n')\r\n> > \r\n> > features = {'x': ['x1', 'x1', 'x2', 'x2', 'x2', 'x1', 'x2'],\r\n> >             'y': ['y1', 'y2', 'y1', 'y2', 'y3', 'y1', 'y3']}\r\n> > \r\n> > pdf = pd.DataFrame(features)\r\n> > pdf = pd.crosstab(index = pdf.x, columns = pdf.y)\r\n> > \r\n> > gdf = cudf.DataFrame(features)\r\n> > gdf = cudf.crosstab(index = gdf.x, columns = gdf.y)\r\n> > \r\n> > print(gdf.to_pandas().equals(pdf), '\\n')\r\n> > print(pdf.columns, '\\n', gdf.columns)\r\n> > \r\n> > 22.10.00a0+g17868b7 1.5.0 \r\n> > \r\n> > False \r\n> > \r\n> > Index(['y1', 'y2', 'y3'], dtype='object', name='y') \r\n> >  MultiIndex([('y1',),\r\n> >             ('y2',),\r\n> >             ('y3',)],\r\n> >            names=['y'])\r\n> \r\n```\r\n\r\n**Expected behavior**\r\nI would like the results between cuDF and Pandas match.","closed":false,"closedAt":null,"comments":[{"id":"IC_kwDOBWUGps5Mu-ek","author":{"login":"GregoryKimball"},"authorAssociation":"CONTRIBUTOR","body":"Thanks @miguelusque for raising this issue. ~I know that we've had trouble supporting the pandas MultiIndex behavior. I believe there was a proposal to drop MultiIndex support - how big of an impact would that be for the users you've worked with?~ To my surprise, it is `cudf` that is generating the `MultiIndex` - we should just return a simple `Index` instead! \r\n\r\n","createdAt":"2022-10-21T20:01:51Z","includesCreatedEdit":true,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/11896#issuecomment-1287382948","viewerDidAuthor":false},{"id":"IC_kwDOBWUGps5Mv-YZ","author":{"login":"miguelusque"},"authorAssociation":"MEMBER","body":"Hi @GregoryKimball , thank you!.\r\n\r\nPlease find below the original code that I was porting from Pandas to cuDF. Unfortunately, `.add_prefix()` and `.and_suffix()` methods do not work with `MultiIndex`.\r\n\r\nOriginal code:\r\n\r\n```python\r\ndf = df.to_pandas()\r\n# Which department have user ordered products?\r\ndf_ = pd.crosstab(df.user_id, df.department_id).add_prefix('user_department_').add_suffix('_freq')\r\nfeature_list.append(cudf.from_pandas(df_))\r\n```\r\n\r\nWorkaround:\r\n\r\n```python\r\n # Which department have user ordered products?\r\ndf_ = cudf.crosstab(df.user_id, df.department_id)\r\ndf_.columns = ['user_department_' + str(c[0]) + '_freq' for c in df_.columns]\r\nfeature_list.append(df_)\r\n```\r\n\r\nHope it helps!","createdAt":"2022-10-22T06:20:19Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/11896#issuecomment-1287644697","viewerDidAuthor":false}],"createdAt":"2022-10-11T08:33:53Z","id":"I_kwDOBWUGps5Tsvhj","labels":[{"id":"MDU6TGFiZWwxMDEzOTg3MzUy","name":"0 - Backlog","description":"In queue waiting for assignment","color":"d4c5f9"},{"id":"MDU6TGFiZWwxMTM5NzQxMjEz","name":"cuDF (Python)","description":"Affects Python cuDF API.","color":"1d76db"}],"milestone":{"number":5,"title":"Pandas API Alignment and Coverage","description":"","dueOn":null},"number":11896,"projectCards":[{"project":{"name":"Bug Squashing"},"column":{"name":"Needs prioritizing"}}],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[BUG] Column types after cudf.crosstab() does not match Pandas result","updatedAt":"2022-10-22T06:20:20Z","url":"https://github.com/rapidsai/cudf/issues/11896"}
