{"assignees":[],"author":{"id":"MDQ6VXNlcjE5OTQ5MjA3","is_bot":false,"login":"ayushdg","name":"Ayush Dattagupta"},"body":"**What is your question?**\r\nOften when reading from files, the data is not utf-8 encoded. In such situations pandas throws a clear `utf-8 decoding error` unless the encoding is specified.\r\n\r\nCudf read_csv on the other hand reads the data without throwing any errors. I can run operations like groupby, etc on my Dataframe. But trying to print or convert to pandas throws the utf-8 errors. \r\n\r\nWould it make sense to throw an error if we encounter non utf-8 charsets (like iso-8859-1 encoding)?\r\nSince cudf does not allow specifying encoding. Would it make more sense to let the behavior stay and allow users to do operations with df's and throw errors while print, converting to string, pandas etc.\r\nOr possibly another option could raise some sort of warning mentioning that the data contains non-utf8 chars (if that's even possible) and let everything run as usual.","closed":false,"closedAt":null,"comments":[],"createdAt":"2019-07-26T19:49:11Z","id":"MDU6SXNzdWU0NzM1MTAwNzk=","labels":[{"id":"MDU6TGFiZWw1OTk2MjY1NjE=","name":"feature request","description":"New feature or request","color":"a2eeef"},{"id":"MDU6TGFiZWwxMTM5NzQwNjY2","name":"libcudf","description":"Affects libcudf (C++/CUDA) code.","color":"c5def5"},{"id":"MDU6TGFiZWwxMTg1MjQ0MTQy","name":"cuIO","description":"cuIO issue","color":"fef2c0"}],"milestone":null,"number":2407,"projectCards":[{"project":{"name":"Feature Planning"},"column":{"name":"Needs prioritizing"}}],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[FEA] Throw exception on non utf-8 charsets during io operations","updatedAt":"2023-04-02T22:38:19Z","url":"https://github.com/rapidsai/cudf/issues/2407"}
