{"assignees":[],"author":{"id":"MDQ6VXNlcjEwNjQ3MDgy","is_bot":false,"login":"mroeschke","name":"Matthew Roeschke"},"body":"**Is your feature request related to a problem? Please describe.**\r\nWhile working on a pandas to cudf workflow comparison, I noticed that `groupby(...).resample(...)` has not been implemented in cudf yet\r\n\r\n**Describe the solution you'd like**\r\n```\r\nIn [26]: from datetime import datetime\r\n\r\nIn [27]: import pandas as pd\r\n\r\nIn [28]: import cudf\r\n\r\nIn [29]: data = {\"group\": list(\"abab\"), \"values\": range(4), \"ts\": [datetime(2023,\r\n    ...:  1, 1), datetime(2023, 1, 2), datetime(2023, 1, 3), datetime(2023, 1, 4)\r\n    ...: ]}\r\n\r\nIn [30]: df = pd.DataFrame(data)\r\n\r\nIn [31]: df.groupby(\"group\").resample(\"D\", on=\"ts\")[\"values\"].mean()\r\nOut[31]:\r\ngroup  ts\r\na      2023-01-01    0.0\r\n       2023-01-02    NaN\r\n       2023-01-03    2.0\r\nb      2023-01-02    1.0\r\n       2023-01-03    NaN\r\n       2023-01-04    3.0\r\nName: values, dtype: float64\r\n\r\nIn [32]: cu_df = cudf.DataFrame(data)\r\n\r\nIn [33]: cu_df.groupby(\"group\").resample(\"D\", on=\"ts\")[\"values\"].mean()\r\nKeyError: 'resample'\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nAttributeError: DataFrameGroupBy object has no attribute resample\r\n```\r\n\r\n**Describe alternatives you've considered**\r\nCan for loop over the groups of `cu_df.groupby(\"group\")` and call `resample` individually.\r\n\r\n**Additional context**\r\nhttps://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.resample.html\r\n","closed":false,"closedAt":null,"comments":[{"id":"IC_kwDOBWUGps5Xb-3Z","author":{"login":"shwina"},"authorAssociation":"CONTRIBUTOR","body":"Perhaps related: https://github.com/rapidsai/cudf/pull/12882","createdAt":"2023-03-13T21:03:05Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/12935#issuecomment-1466953177","viewerDidAuthor":false},{"id":"IC_kwDOBWUGps5Xo8tG","author":{"login":"wence-"},"authorAssociation":"CONTRIBUTOR","body":"Resampling is somewhat different, I _think_. One possible implementation might be to produce the grouped dataframe and then call `DataFrame.resample` on the whole thing (since I _think_ that the resampling commutes with grouping)","createdAt":"2023-03-15T16:25:25Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/12935#issuecomment-1470352198","viewerDidAuthor":false}],"createdAt":"2023-03-13T20:47:18Z","id":"I_kwDOBWUGps5gsVZy","labels":[{"id":"MDU6TGFiZWw1OTk2MjY1NjE=","name":"feature request","description":"New feature or request","color":"a2eeef"}],"milestone":null,"number":12935,"projectCards":[],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[FEA]: Support groupby.resample","updatedAt":"2024-02-23T18:02:40Z","url":"https://github.com/rapidsai/cudf/issues/12935"}
