{"assignees":[],"author":{"id":"MDQ6VXNlcjg3Mzc2Mzg0","is_bot":false,"login":"Kkrishnaa","name":""},"body":"**What is your question?**\r\nGot different results when trying to convert dictionary to dataframe using pandas and cudf\r\n![image](https://user-images.githubusercontent.com/87376384/125461623-98da6483-d5eb-4278-bdeb-944276949a5e.png)\r\n","closed":false,"closedAt":null,"comments":[{"id":"MDEyOklzc3VlQ29tbWVudDg3OTEwMzMzNg==","author":{"login":"beckernick"},"authorAssociation":"MEMBER","body":"Thanks for filing an issue @Kkrishnaa . It looks like the cuDF DataFrame constructor is not able to handle the nested dictionary input.\r\n\r\n```python\r\nimport cudf\r\nimport pandas as pd\r\n​\r\nd = {\"a\": {\"b\":[1,2,3,4]}}\r\n​\r\nprint(pd.DataFrame(d))\r\nprint(cudf.DataFrame(d))\r\n              a\r\nb  [1, 2, 3, 4]\r\n   a\r\n0  b\r\n```\r\n\r\nIn the future, if you believe you've run into a bug, please select the \"Bug Report\" issue option and follow [this guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.","createdAt":"2021-07-13T13:47:09Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/8725#issuecomment-879103336","viewerDidAuthor":false},{"id":"IC_kwDOBWUGps408l0t","author":{"login":"beckernick"},"authorAssociation":"MEMBER","body":"As a note, this outcome can be accomplished today by representing the original data differently (as a list of lists, with a separate index list):\r\n\r\n```python\r\nimport cudf\r\n​\r\ndf = cudf.DataFrame({\r\n    \"a\":[\r\n        [1,2,3,4],\r\n        [2,3,4,5]\r\n    ]},\r\n    index=[\"b\", \"c\"]\r\n)\r\nprint(df)\r\n              a\r\nb  [1, 2, 3, 4]\r\nc  [2, 3, 4, 5]\r\n```","createdAt":"2021-07-28T13:13:23Z","includesCreatedEdit":true,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/8725#issuecomment-888298797","viewerDidAuthor":false},{"id":"IC_kwDOBWUGps45xp7p","author":{"login":"github-actions"},"authorAssociation":"NONE","body":"This issue has been labeled `inactive-90d` due to no recent activity in the past 90 days. Please close this issue if no further response or action is needed. Otherwise, please respond with a comment indicating any updates or changes to the original issue and/or confirm this issue still needs to be addressed.","createdAt":"2021-11-15T21:03:13Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/8725#issuecomment-969318121","viewerDidAuthor":false}],"createdAt":"2021-07-13T13:38:28Z","id":"MDU6SXNzdWU5NDMzOTU4NDU=","labels":[{"id":"MDU6TGFiZWw1OTk2MjY1NTk=","name":"bug","description":"Something isn't working","color":"d73a4a"},{"id":"MDU6TGFiZWwxMTM5NzQxMjEz","name":"cuDF (Python)","description":"Affects Python cuDF API.","color":"1d76db"}],"milestone":{"number":2,"title":"List and Struct data types and operations","description":"","dueOn":null},"number":8725,"projectCards":[{"project":{"name":"Bug Squashing"},"column":{"name":"Needs prioritizing"}}],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[BUG] DataFrame constructor incorrectly loads nested dictionary input","updatedAt":"2024-02-23T18:42:20Z","url":"https://github.com/rapidsai/cudf/issues/8725"}
