{"assignees":[],"author":{"id":"MDQ6VXNlcjQ2OTM1MTQw","is_bot":false,"login":"taureandyernv","name":"Taurean Dyer"},"body":"## Report incorrect documentation\r\n\r\n**Location of incorrect documentation**\r\nhttps://docs.rapids.ai/api/cudf/stable/api_docs/api/cudf.DataFrame.mode.html?highlight=mode#cudf.DataFrame.mode\r\n\r\n**Describe the problems or issues found in the documentation**\r\nDocumentation says that mode can be applied over columns (axis = 0) or rows (axis = 1), but when trying axis = 1, it says `Only axis=0 is currently supported`\r\n\r\n**Steps taken to verify documentation is incorrect**\r\n\r\n```\r\nimport cudf\r\ndf = cudf.DataFrame(np.random.randint(0,5,size=(15, 10)), columns=list('ABCDEFGHIJ'))\r\ndf.mode(axis=1)\r\n```\r\nStack trace\r\n```\r\n---------------------------------------------------------------------------\r\nNotImplementedError                       Traceback (most recent call last)\r\n/tmp/ipykernel_2243/3323872345.py in <module>\r\n----> 1 df.mode(axis=1)\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/contextlib.py in inner(*args, **kwds)\r\n     73         def inner(*args, **kwds):\r\n     74             with self._recreate_cm():\r\n---> 75                 return func(*args, **kwds)\r\n     76         return inner\r\n     77 \r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/dataframe.py in mode(self, axis, numeric_only, dropna)\r\n   5678         \"\"\"\r\n   5679         if axis not in (0, \"index\"):\r\n-> 5680             raise NotImplementedError(\"Only axis=0 is currently supported\")\r\n   5681 \r\n   5682         if numeric_only:\r\n\r\nNotImplementedError: Only axis=0 is currently supported\r\n```\r\n**Suggested fix for documentation**\r\nEither \r\n1. state that axis = 1 is not supported\r\n2. remove references for axis = 1 in docs\r\n3. add the functionality\r\n","closed":false,"closedAt":null,"comments":[{"id":"IC_kwDOBWUGps5IyM8F","author":{"login":"bdice"},"authorAssociation":"CONTRIBUTOR","body":"In this case, `df.T.mode(axis=0).T` might solve the problem as expected. Generally, there are quite a few places where keyword arguments (especially `axis`) are documented, but non-default values are not yet supported.","createdAt":"2022-08-19T21:55:22Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/11570#issuecomment-1221119749","viewerDidAuthor":false},{"id":"IC_kwDOBWUGps5Kh4R7","author":{"login":"github-actions"},"authorAssociation":"NONE","body":"This issue has been labeled `inactive-30d` due to no recent activity in the past 30 days. Please close this issue if no further response or action is needed. Otherwise, please respond with a comment indicating any updates or changes to the original issue and/or confirm this issue still needs to be addressed. This issue will be labeled `inactive-90d` if there is no activity in the next 60 days.","createdAt":"2022-09-18T22:02:55Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/11570#issuecomment-1250395259","viewerDidAuthor":false}],"createdAt":"2022-08-19T15:42:58Z","id":"I_kwDOBWUGps5QJQ4d","labels":[{"id":"MDU6TGFiZWwxMDEzOTg3NDE3","name":"1 - On Deck","description":"To be worked on next","color":"bfd4f2"},{"id":"MDU6TGFiZWwxMDEzOTg5MDIz","name":"doc","description":"Documentation","color":"1C62F8"},{"id":"MDU6TGFiZWwxMTM5NzQxMjEz","name":"cuDF (Python)","description":"Affects Python cuDF API.","color":"1d76db"}],"milestone":null,"number":11570,"projectCards":[{"project":{"name":"Other Issues"},"column":{"name":"Needs prioritizing"}}],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[DOC] `.mode()` incorrectly states that axis=1 is supported as it throws \"NotImplementedError\" when you try","updatedAt":"2022-10-21T07:30:51Z","url":"https://github.com/rapidsai/cudf/issues/11570"}
